# Generated by Django 4.2.6 on 2023-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0002_movie_image_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10),
        ),
    ]
